/* generated by scripts/build-pwa-service-worker.mjs */
const CACHE_PREFIX = "gomoku-mark-pwa-";
const CACHE_NAME = "gomoku-mark-pwa-3e0b4584884550c5";
const PRECACHE_URLS = [
  "./.gitkeep",
  "./THIRD-PARTY-NOTICES.txt",
  "./assets/index-C6z3aOhu.js",
  "./assets/index-cwTAQUAI.css",
  "./assets/learning.worker-CJhVQMhe.js",
  "./assets/search.worker-D0hfloen.js",
  "./assets/studio-black-Dz8N1kpl.wav",
  "./assets/studio-draw-BIG69AWi.wav",
  "./assets/studio-loss-JjDF934f.wav",
  "./assets/studio-start-DRL3dUkm.wav",
  "./assets/studio-white-DGfebr2j.wav",
  "./assets/studio-win-B0Rd7aoE.wav",
  "./build-info.json",
  "./fonts/NotoSansSC-OFL.txt",
  "./fonts/NotoSansTC-OFL.txt",
  "./fonts/forge-sans-sc-ui.woff2",
  "./fonts/forge-sans-tc-ui.woff2",
  "./fonts/sources.json",
  "./fonts/subsets.json",
  "./icons/gomoku-mark-192.png",
  "./icons/gomoku-mark-512.png",
  "./icons/gomoku-mark.svg",
  "./icons/study-seal.svg",
  "./images/ui/home-board-v2.png",
  "./index.html",
  "./licenses/Electron-MIT.txt",
  "./licenses/React-MIT.txt",
  "./manifest.webmanifest",
  "./rapfi/COPYING.txt",
  "./rapfi/NETWORKS-LICENSE.txt",
  "./rapfi/SOURCE.md",
  "./rapfi/expert/SOURCE.md",
  "./rapfi/expert/rapfi-single-simd128.data",
  "./rapfi/expert/rapfi-single-simd128.js",
  "./rapfi/expert/rapfi-single-simd128.wasm",
  "./rapfi/expert/rapfi.worker.js",
  "./rapfi/rapfi-diagnostics.js",
  "./rapfi/rapfi-loader.js"
];
const NAVIGATION_STRATEGY = "network-first";
const STATIC_STRATEGY = "cache-first";
const RAPFI_PATH_PREFIX = new URL("./rapfi/", self.registration.scope).pathname;
const LAZY_ASSETS = {"./assets/quiet-board-BDVj52Pc.ogg":"72889f90b043d30fff9b4b4d0d5dd57caef39a6e71d4c04c2e8c363bf7e89284","./assets/studio-air-DwbdNTrm.wav":"e27c9d81782de5c4199b8e7a45f6b8293627d38b6568589795bc84174a469eb9","./rapfi/rapfi-single-simd128.data":"472d3c9459cac77bf5937162eefc1faadfaefe296e361f756370142e7765e1df","./rapfi/rapfi-single-simd128.js":"e7a6f22f99077bae5ff7dd1626d49733c554e87c6aef9e500339f5d7d641222a","./rapfi/rapfi-single-simd128.wasm":"e746664530b4ddd5f2c7c6af611c36d832700c6ae8311f1afed4e7ed229d92fb","./rapfi/rapfi.worker.js":"49ff80691eb6a6019267f59c74db510881f3d19d661d6b7806812267183773eb"};
const ENGINE_ASSETS = "c7c29eff0df3b1f3";

function scopedUrl(relativePath) {
  return new URL(relativePath, self.registration.scope).href;
}

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) =>
      cache.addAll(PRECACHE_URLS.map((relativePath) => scopedUrl(relativePath)))
    )
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) =>
      Promise.all(
        cacheNames
          .filter(
            (cacheName) =>
              cacheName.startsWith(CACHE_PREFIX) && cacheName !== CACHE_NAME
          )
          .map((cacheName) => caches.delete(cacheName))
      )
    ).then(() => self.clients.claim())
  );
});

// Cache full media files only, then answer a single Range request from that copy.
async function rangedResponse(request, response) {
  const range = request.headers.get("Range");
  if (!range) return response;
  const match = /^bytes=(\d*)-(\d*)$/.exec(range);
  if (!match || (!match[1] && !match[2])) return new Response(null, { status: 416 });
  const bytes = await response.arrayBuffer();
  const size = bytes.byteLength;
  const start = match[1] ? Number(match[1]) : Math.max(0, size - Number(match[2]));
  const end = match[1] && match[2] ? Math.min(Number(match[2]), size - 1) : size - 1;
  if (start > end || start >= size) return new Response(null, { status: 416, headers: { "Content-Range": "bytes */" + size } });
  const headers = new Headers(response.headers);
  headers.set("Content-Range", "bytes " + start + "-" + end + "/" + size);
  headers.set("Content-Length", String(end - start + 1));
  headers.set("Accept-Ranges", "bytes");
  return new Response(bytes.slice(start, end + 1), { status: 206, headers });
}

async function lazyResponse(request, cache, key, expectedHash) {
  let response = await cache.match(key);
  if (!response) {
    const headers = new Headers(request.headers);
    headers.delete("Range");
    response = await fetch(new Request(request, { headers }));
    if (response.status !== 200) return response;
    const digest = await crypto.subtle.digest("SHA-256", await response.clone().arrayBuffer());
    const actualHash = Array.from(new Uint8Array(digest), byte => byte.toString(16).padStart(2, "0")).join("");
    // Do not persist or serve an asset from a different deployment.
    if (actualHash !== expectedHash) return Response.error();
    await cache.put(key, response.clone());
  }
  return rangedResponse(request, response);
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== "GET" || url.origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request)
        .catch(() =>
          caches
            .open(CACHE_NAME)
            .then((cache) => cache.match(scopedUrl("./index.html")))
            .then((response) => response || Response.error())
        )
    );
    return;
  }

  event.respondWith(
    caches.open(CACHE_NAME).then(async (cache) => {
      const lazyKey = Object.keys(LAZY_ASSETS).find(key => new URL(key, self.registration.scope).pathname === url.pathname);
      if (url.pathname.startsWith(RAPFI_PATH_PREFIX)) {
        // A waiting update must not mix its engine with the active client's assets.
        const requestedAssets = url.searchParams.get("assets");
        if (requestedAssets && requestedAssets !== ENGINE_ASSETS) return fetch(request);
        if (lazyKey) return lazyResponse(request, cache, scopedUrl(lazyKey), LAZY_ASSETS[lazyKey]);
        const cachedEngine = await cache.match(request, { ignoreSearch: true, ignoreVary: true });
        if (cachedEngine) return cachedEngine;
        return fetch(request);
      }
      if (lazyKey) return lazyResponse(request, cache, scopedUrl(lazyKey), LAZY_ASSETS[lazyKey]);
      const cached = await cache.match(request, { ignoreVary: true });
      if (cached) return cached;
      const response = await fetch(request);
      if (response.ok) {
        void cache.put(request, response.clone()).catch(() => undefined);
      }
      return response;
    })
  );
});
