/* generated by scripts/build-pwa-service-worker.mjs */
const CACHE_PREFIX = "gomoku-mark-pwa-";
const CACHE_NAME = "gomoku-mark-pwa-90412fe5e6c73864";
const PRECACHE_URLS = [
  "./.gitkeep",
  "./THIRD-PARTY-NOTICES.txt",
  "./assets/index-BJKChXik.css",
  "./assets/index-BwPER5uU.js",
  "./assets/quiet-board-BDVj52Pc.ogg",
  "./assets/search.worker-D0hfloen.js",
  "./assets/studio-air-DwbdNTrm.wav",
  "./assets/studio-black-Dz8N1kpl.wav",
  "./assets/studio-draw-BIG69AWi.wav",
  "./assets/studio-loss-JjDF934f.wav",
  "./assets/studio-start-DRL3dUkm.wav",
  "./assets/studio-white-DGfebr2j.wav",
  "./assets/studio-win-B0Rd7aoE.wav",
  "./build-info.json",
  "./icons/gomoku-mark-192.png",
  "./icons/gomoku-mark-512.png",
  "./icons/gomoku-mark.svg",
  "./index.html",
  "./licenses/Electron-MIT.txt",
  "./licenses/React-MIT.txt",
  "./manifest.webmanifest",
  "./rapfi/COPYING.txt",
  "./rapfi/NETWORKS-LICENSE.txt",
  "./rapfi/SOURCE.md",
  "./rapfi/expert/SOURCE.md",
  "./rapfi/expert/rapfi-single-simd128.data",
  "./rapfi/expert/rapfi-single-simd128.js",
  "./rapfi/expert/rapfi-single-simd128.wasm",
  "./rapfi/expert/rapfi.worker.js",
  "./rapfi/rapfi-diagnostics.js",
  "./rapfi/rapfi-loader.js",
  "./rapfi/rapfi-single-simd128.data",
  "./rapfi/rapfi-single-simd128.js",
  "./rapfi/rapfi-single-simd128.wasm",
  "./rapfi/rapfi.worker.js"
];
const NAVIGATION_STRATEGY = "network-first";
const STATIC_STRATEGY = "cache-first";
const RAPFI_PATH_PREFIX = new URL("./rapfi/", self.registration.scope).pathname;
const ENGINE_ASSETS = "c7c29eff0df3b1f3";

function scopedUrl(relativePath) {
  return new URL(relativePath, self.registration.scope).href;
}

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) =>
      cache.addAll(PRECACHE_URLS.map((relativePath) => scopedUrl(relativePath)))
    )
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) =>
      Promise.all(
        cacheNames
          .filter(
            (cacheName) =>
              cacheName.startsWith(CACHE_PREFIX) && cacheName !== CACHE_NAME
          )
          .map((cacheName) => caches.delete(cacheName))
      )
    ).then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== "GET" || url.origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request)
        .catch(() =>
          caches
            .open(CACHE_NAME)
            .then((cache) => cache.match(scopedUrl("./index.html")))
            .then((response) => response || Response.error())
        )
    );
    return;
  }

  event.respondWith(
    caches.open(CACHE_NAME).then(async (cache) => {
      if (url.pathname.startsWith(RAPFI_PATH_PREFIX)) {
        // A waiting update must not mix its engine with the active client's assets.
        const requestedAssets = url.searchParams.get("assets");
        if (requestedAssets && requestedAssets !== ENGINE_ASSETS) return fetch(request);
        const cachedEngine = await cache.match(request, { ignoreSearch: true, ignoreVary: true });
        if (cachedEngine) return cachedEngine;
        return fetch(request);
      }
      const cached = await cache.match(request, { ignoreVary: true });
      if (cached) return cached;
      const response = await fetch(request);
      if (response.ok) {
        void cache.put(request, response.clone()).catch(() => undefined);
      }
      return response;
    })
  );
});
